# Generated by Django 2.2 on 2020-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_auto_20200424_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='fb_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
