# Generated by Django 2.2 on 2020-04-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20200426_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='fb_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
